const names = require('./4-names')
const sayHi = require('./5-utils.js')
const data = require('./6-alternative-flavour')
require('./7-mind-granade')
sayHi('susan')
sayHi(names.john)
sayHi(names.peter)